CREATE OR REPLACE TRIGGER BOOK_COPY_DELETE
AFTER INSERT
ON ORDERS
FOR EACH ROW
DECLARE
QUAN INTEGER;
B_ID INTEGER;
S_ID INTEGER;
X INTEGER;
BEGIN
		X := 0;
		QUAN:= :NEW.QUANTITY;
		B_ID := :NEW.BOOK_ID;
		S_ID:= :NEW.SHOP_ID;
		FOR R IN (SELECT BOOK_COPY_ID FROM BOOK_COPY WHERE BOOK_ID= B_ID AND SHOP_ID= S_ID) 
		LOOP
		DELETE FROM BOOK_COPY WHERE BOOK_COPY_ID= R.BOOK_COPY_ID;
		X := X+1;
		EXIT WHEN X= QUAN;
		END LOOP;
END;
