--INSERT INTO CART_DETAILS VALUES(10001020, 3, 20020, 150);

CREATE OR REPLACE PROCEDURE ADD_ORDER(b_id IN INTEGER, c_id IN INTEGER, s_id IN INTEGER, b_quantity IN NUMBER, b_total IN NUMBER, o_transaction IN VARCHAR2, astreet IN VARCHAR2, athana IN VARCHAR2, apostal_code IN VARCHAR2, dname IN VARCHAR2) IS
dist_id INTEGER ;
a_id INTEGER ;
i INTEGER;
j INTEGER;
BEGIN
		--add district
		i := 0;
		FOR R IN (SELECT DISTRICT_NAME FROM DISTRICT) 
		LOOP
				IF UPPER(R.DISTRICT_NAME)= UPPER(dname) THEN
						i :=1;
			  END IF;
				EXIT WHEN i=1; 
		END LOOP;
		IF i=0 THEN
				INSERT INTO DISTRICT(DISTRICT_NAME) VALUES(dname);
		END IF;
		SELECT DISTRICT_ID INTO dist_id FROM DISTRICT WHERE UPPER(DISTRICT_NAME)= UPPER(dname);
		
		--Add_Address
		j := 0;
		FOR R1 IN (SELECT STREET, THANA FROM ADDRESS_DETAIL) 
		LOOP
				IF UPPER(R1.STREET)= UPPER(astreet) AND UPPER(R1.THANA)= UPPER(athana) THEN
						j :=1;
			  END IF;
				EXIT WHEN j=1; 
		END LOOP;
		IF j=0 THEN
				INSERT INTO ADDRESS_DETAIL(street, thana, postal_code, DISTRICT_ID) VALUES(astreet, athana, apostal_code, dist_id);
		END IF;
		SELECT ADDRESS_ID INTO a_id FROM ADDRESS_DETAIL WHERE UPPER(street)= UPPER(astreet) AND UPPER(THANA)= UPPER(athana);
		INSERT INTO ORDERS(BOOK_ID, CUSTOMER_ID, SHOP_ID, QUANTITY, TOTAL_PRICE, TRANSACTION_ID, ADDRESS_ID) VALUES(b_id, c_id, s_id, b_quantity, b_total,o_transaction, a_id);
END;

DECLARE
BEGIN
		ADD_ORDER(10001020, 3, 20020, 3, 450, 'ASSASHSD454', 'Nobinagar', 'Hoogly', 1245, 'Shiliguri');
END;
